# Compilação e Testes

name: CI - Spring Boot Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Compilar com Maven
        run: mvn -B clean compile

      - name: Executar testes
        run: mvn -B test

      - name: Build jar
        run: mvn -B package -DskipTests

      - name: Upload do artefato (jar)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
